title: flysoft's blog
email: flysoftbeta@outlook.com
description: >-
  The place where flysoft documents the
  thoughts/experience of working with compilers/kernel/algorithms
baseurl: ""
url: ""
permalink: /posts/:name/
github_username: FlysoftBeta

markdown: kramdown
kramdown:
  math_engine: katex

theme: minima
sass:
  quiet_deps: true
  silence_deprecations:
    - import
plugins:
  - jekyll-feed

exclude:
  - Rakefile
