title: flysoft's blog
email: flysoftbeta@outlook.com
description: >-
  the thoughts/ideas with compilers/kernel/algorithms
baseurl: ""
url: ""
permalink: /posts/:name/
github_username: FlysoftBeta

markdown: kramdown
kramdown:
  math_engine: katex

theme: minima
minima:
  social_links:
    - { icon: github, url: "https://github.com/FlysoftBeta" }
    - { icon: bilibili, url: "https://space.bilibili.com/3493090792835786" }
sass:
  quiet_deps: true
  silence_deprecations:
    - import
plugins:
  - jekyll-feed

exclude:
  - Rakefile
