title: flysoft's blog
author:
  name: FlysoftBeta
  email: flysoftbeta@outlook.com
description: >-
  computer science lab for half-baked ideas
baseurl: ""
url: "https://flysoftbeta.top"
permalink: /posts/:name/
github_username: FlysoftBeta

markdown: kramdown
kramdown:
  math_engine: katex

theme: minima
minima:
  social_links:
    - { icon: github, url: "https://github.com/FlysoftBeta" }
    - { icon: bilibili, url: "https://space.bilibili.com/3493090792835786" }
sass:
  quiet_deps: true
  silence_deprecations:
    - import
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Rakefile
